
CREATE TABLE USUARIO (
ID_USUARIO INT NOT  NULL auto_increment,
NOME VARCHAR(50),
IDADE int,
PRIMARY KEY (ID_USUARIO)
);
 
CREATE TABLE RECEITA (
ID_RECEITA INT NOT  NULL auto_increment,
ID_USUARIO INT,
NOME_RECEITA VARCHAR(100),
DESCRICAO_RECEITA VARCHAR(50),
VALOR_RECEITA DOUBLE,
IMAGEM_RECEITA VARCHAR(255),
PRIMARY KEY (ID_RECEITA),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
 
CREATE TABLE DESPESA (
ID_DESPESA INT NOT  NULL auto_increment,
ID_RECEITA INT,
ID_USUARIO INT, 
NOME_DESPESA VARCHAR(100),
DESCRICAO_DESPESA VARCHAR(50),
VALOR_DESPESA DOUBLE,
IMAGEM_DESPESA VARCHAR(255), 
PRIMARY KEY (ID_DESPESA),
FOREIGN KEY (ID_RECEITA) REFERENCES RECEITA(ID_RECEITA),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
 
CREATE TABLE LOGIN (
ID_LOGIN INT NOT  NULL auto_increment,
ID_USUARIO INT,
USUARIO_LOGIN VARCHAR(50),
USUARIO_SENHA VARCHAR(50),
PRIMARY KEY (ID_LOGIN),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
 
INSERT INTO USUARIO (NOME, IDADE) VALUES ('RICARDO', 22);
INSERT INTO LOGIN (ID_USUARIO, USUARIO_LOGIN, USUARIO_SENHA) VALUES ((SELECT ID_USUARIO FROM USUARIO WHERE NOME = 'RICARDO'), "RICARDO@LOGIN", '@Senha01');
INSERT INTO RECEITA (ID_USUARIO, NOME_RECEITA, DESCRICAO_RECEITA, VALOR_RECEITA, IMAGEM_RECEITA) VALUE ((SELECT ID_USUARIO FROM USUARIO WHERE NOME = 'RICARDO'), 'Salário', 'Salário já descontado', '1849', 'http://192.168.15.5/img/plus-solid.svg');
INSERT INTO DESPESA (ID_USUARIO, NOME_DESPESA, DESCRICAO_DESPESA, VALOR_DESPESA, IMAGEM_DESPESA) VALUE ((SELECT ID_USUARIO FROM USUARIO WHERE NOME = 'RICARDO'), 'Shopping', 'Compra de sapatos', '220', 'http://192.168.15.5/img/minus-solid.svg');


UPDATE RECEITA SET RECEITA_IMAGEM = 'http://192.168.15.5/img/plus-solid.svg' WHERE ID_USUARIO = 2;
UPDATE DESPESA SET DESPESA_IMAGEM = 'http://192.168.15.5/img/minus-solid.svg' WHERE ID_USUARIO = 2;
TRUNCATE RECEITA;

