
CREATE TABLE USUARIO (
ID_USUARIO INT NOT  NULL auto_increment,
NOME VARCHAR(50),
IDADE int,
PRIMARY KEY (ID_USUARIO)
);
 
CREATE TABLE CONTRIBUICAO (
ID_CONTRIBUICAO INT NOT  NULL auto_increment,
ID_USUARIO INT,
VALOR_CONTRIBUICAO DOUBLE,
PRIMARY KEY (ID_CONTRIBUICAO),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
 
CREATE TABLE DESPESA (
ID_DESPESA INT NOT  NULL auto_increment,
ID_CONTRIBUICAO INT,
DESCRICAO_DESPESA VARCHAR(50),
VALOR_DESPESA DOUBLE,
STATUS_DESPESA VARCHAR(10),
PRIMARY KEY (ID_DESPESA),
FOREIGN KEY (ID_CONTRIBUICAO) REFERENCES CONTRIBUICAO(ID_CONTRIBUICAO)
);
 
CREATE TABLE LOGIN (
ID_LOGIN INT NOT  NULL auto_increment,
ID_USUARIO INT,
USUARIO_LOGIN VARCHAR(50),
USUARIO_SENHA VARCHAR(50),
PRIMARY KEY (ID_LOGIN),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
 
INSERT INTO USUARIO (NOME, IDADE) VALUES ('JOSE', 40);
INSERT INTO LOGIN (ID_USUARIO, USUARIO_LOGIN, USUARIO_SENHA) VALUES (1, "JOSE@LOGIN", '@Senha01');

SELECT * FROM USUARIO;